default: &default
  url: <%= ENV['REDIS_URL'] %>
  pool: <%= ENV.fetch('REDIS_POOL') { ENV.fetch('RAILS_MAX_THREADS') { 5 } } %>

development:
  <<: *default
  namespace: <%= ENV.fetch('REDIS_NAMESPACE') { 'scalelite_development' } %>


test:
  <<: *default
  url: <%= ENV['TEST_REDIS_URL'] || 'redis://localhost:6379/1' %> # Set the Redis URL for the test environment
  namespace: scalelite_test

production:
  <<: *default
  namespace: <%= ENV.fetch('REDIS_NAMESPACE') { 'scalelite' } %>
