#!/bin/sh

if [ $$ == 1 ]; then
	echo "Startup script was run as init, re-execing using tini."
	exec /sbin/tini -- $0 "$@"
fi

echo "Generating templated nginx configuration..."
if [ -n "$NGINX_SSL" ] ; then
	echo "Using SSL configuration template."
	nginx_template=/etc/nginx/conf.d/scalelite-ssl.template
else
	echo "Using non-SSL configuration template."
	nginx_template=/etc/nginx/conf.d/scalelite.template
fi
envsubst '$URL_HOST' <$nginx_template >/etc/nginx/conf.d/scalelite.conf
unset nginx_template

mkdir -p /run/nginx

echo "Starting nginx periodic reload process..."
while :; do
	sleep 6h 
	echo "Reloading nginx..."
	nginx -s reload
done &


echo "Starting nginx..."
exec nginx -g 'daemon off;'
