env:
  RUBY_VERSION: 2.7.2

name: Repository Dispatch
on:
  repository_dispatch:
    types: trigger-build
    branches: "*"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push nginx
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: nginx
          tags: ghcr.io/${{ github.repository_owner }}/scalelite-nginx:{{ github.ref }}
      -
        name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: api
          tags: ghcr.io/${{ github.repository_owner }}/scalelite-api:{{ github.ref }}
      -
        name: Build and push poller
        id: docker_build_poller
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: poller
          tags: ghcr.io/${{ github.repository_owner }}/scalelite-poller:{{ github.ref }}
      -
        name: Build and push recording importer
        id: docker_build_recording_importer
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: recording-importer
          tags: ghcr.io/${{ github.repository_owner }}/scalelite-recording-importer:{{ github.ref }}
